### ISSUE TITLE
eel 'options' deprecated

### ISSUE THREAD

**Issue by noraj** [dfd-tud/deda#16]
```
$ python --version
Python 3.7.4
$ python -m venv venv
$ source venv/bin/activate
$ pip install deda
$ deda_gui
Traceback (most recent call last):
  File "/tmp/deda/venv/bin/deda_gui", line 10, in <module>
    sys.exit(main())
  File "/tmp/deda/venv/lib/python3.7/site-packages/deda_gui/deda_gui.py", line 415, in main
    eel.start('index.html', options=web_app_options)
  File "/tmp/deda/venv/lib/python3.7/site-packages/eel/__init__.py", line 118, in start
    raise RuntimeError(api_error_message)
RuntimeError: 
----------------------------------------------------------------------------------
  'options' argument deprecated in v1.0.0, see https://github.com/ChrisKnott/Eel
  To suppress this error, add 'suppress_error=True' to start() call.
  This option will be removed in future versions
----------------------------------------------------------------------------------
```

**Comment by timojuez** [comment]
Thank you. Merged in dev branch.
