### ISSUE TITLE
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7ffeefadcfe0> 

### ISSUE THREAD

**Issue by p1r473** [dfd-tud/deda#27]
```
❯ deda_anonmask_create -w
testpage.pdf written.                                                                                                                                    
❯ deda_parse_print testpage.pdf
Traceback (most recent call last):
  File "/root/.local/bin/deda_parse_print", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/.local/lib/python3.11/site-packages/deda_bin/deda_parse_print.py", line 83, in <lambda>
    main = lambda:Main()()
                  ^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/deda_bin/deda_parse_print.py", line 40, in __call__
    pp = PrintParser(fp.read(),ydxArgs=dict(mask=self.args.mask,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/libdeda/print_parser.py", line 67, in __init__
    self._createYD_instance(ydColourRange=cp)
  File "/root/.local/lib/python3.11/site-packages/libdeda/print_parser.py", line 87, in _createYD_instance
    yd = YDX(**ydxArgs)
         ^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/libdeda/extract_yd.py", line 616, in __init__
    CommonImageFunctions.__init__(
  File "/root/.local/lib/python3.11/site-packages/libdeda/extract_yd.py", line 136, in __init__
    self.imgDpi = inputDpi if inputDpi else self.getImgDpi(image)
                                            ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/libdeda/extract_yd.py", line 143, in getImgDpi
    with Image.open(im) as pilimg:
         ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 3283, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fff174d6ac0>  
```

**Comment by timojuez** [comment]
Hey.

I don't really remember if we support pdf input. Can you try with png?

p1r473 ***@***.***> schrieb am Fr., 5. Apr. 2024, 14:37:

**Comment by p1r473** [comment]
The readme says you can create a file with `deda_create_dots PDFINPUT` so I was trying to create the dots on a pdf, and then parse them to test. So, it should
But, it does work with an image file.

**Comment by p1r473** [comment]
It looks like dots can be created on a pdf only, so how can I test that pdf?
❯ deda_create_dots Resume.pdf
❯ deda_parse_print Cardio.png
No tracking dot pattern detected. For best results try a 300 dpi scan and a lossless file format.                                                        2.22s
❯ deda_create_dots Cardio.png

```
REDACTED
        37 dots.



Traceback (most recent call last):
  File "/root/.local/bin/deda_create_dots", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/.local/lib/python3.11/site-packages/deda_bin/deda_create_dots.py", line 60, in <lambda>
    main = lambda:Main()()
                  ^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/deda_bin/deda_create_dots.py", line 56, in __call__
    pdfout.write(aa.apply(pdfin.read()))
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/libdeda/privacy.py", line 305, in apply
    inPdf = self.pdfNormaliseFormat(inPdf,*self.pagesize) # force A4
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/libdeda/privacy.py", line 361, in pdfNormaliseFormat
    input_ = PdfReader(BytesIO(pdfin))
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/PyPDF2/_reader.py", line 319, in __init__
    self.read(stream)
  File "/root/.local/lib/python3.11/site-packages/PyPDF2/_reader.py", line 1415, in read
    self._find_eof_marker(stream)
  File "/root/.local/lib/python3.11/site-packages/PyPDF2/_reader.py", line 1471, in _find_eof_marker
    raise PdfReadError("EOF marker not found")
PyPDF2.errors.PdfReadError: EOF marker not found                                 
```

**Comment by p1r473** [comment]
Doesnt seem like I can test the testpage either
```
s
❯ deda_anonmask_create -w
testpage.pdf written.                                                                                                                                    1.48s
❯ deda_parse_print testpage.pdf
Traceback (most recent call last):
  File "/root/.local/bin/deda_parse_print", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/.local/lib/python3.11/site-packages/deda_bin/deda_parse_print.py", line 83, in <lambda>
    main = lambda:Main()()
                  ^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/deda_bin/deda_parse_print.py", line 40, in __call__
    pp = PrintParser(fp.read(),ydxArgs=dict(mask=self.args.mask,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/libdeda/print_parser.py", line 67, in __init__
    self._createYD_instance(ydColourRange=cp)
  File "/root/.local/lib/python3.11/site-packages/libdeda/print_parser.py", line 87, in _createYD_instance
    yd = YDX(**ydxArgs)
         ^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/libdeda/extract_yd.py", line 616, in __init__
    CommonImageFunctions.__init__(
  File "/root/.local/lib/python3.11/site-packages/libdeda/extract_yd.py", line 136, in __init__
    self.imgDpi = inputDpi if inputDpi else self.getImgDpi(image)
                                            ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/libdeda/extract_yd.py", line 143, in getImgDpi
    with Image.open(im) as pilimg:
         ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 3283, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fff174d6ac0>  
```

**Comment by p1r473** [comment]
Same error when I do
`deda_anonamask_Create -r image.pdf`
This is preventing successful Anonymization of a document for printing

I am following the directions exactly:
Save your document as a PDF file and call it DOCUMENT.PDF.

Print the testpage.pdf file created by
$ deda_anonmask_create -w
without any page margin.

Scan the document (300 dpi) and pass the lossless file to
$ deda_anonmask_create -r INPUTFILE
This creates 'mask.json', the individual printer's anonymisation mask.

Now apply the anonymisation mask:
$ deda_anonmask_apply mask.json DOCUMENT.PDF This creates 'masked.pdf', the anonymised document. It may be printed with a zero page margin setting.

**Comment by p1r473** [comment]
The issue seems to be the application cant find the image on the test page

**Comment by p1r473** [comment]
You were right, had to use an image and not a pdf.
