### ISSUE TITLE
Exception will occur on some png files

### ISSUE THREAD

**Issue by tuxmaster** [dfd-tud/deda#4]
On some png files it will fails with:

> ./deda_parse_print.py a.png 

```
Traceback (most recent call last):
  File "./deda_parse_print.py", line 77, in <module>
    Main()()
  File "./deda_parse_print.py", line 41, in __call__
    verbose=self.args.verbose)
  File "/tmp/deda/libdeda/print_parser.py", line 88, in __init__
    self.pattern = self._calcPattern()
  File "/tmp/deda/libdeda/print_parser.py", line 152, in _calcPattern
    if len(ci)>0 and patternLimits[ci[0][0]] == -1:
UnboundLocalError: local variable 'ci' referenced before assignment

```

**Comment by timojuez** [comment]
Thank you. In this case not any tracking dot pattern could be found in your image. In the development branch this has been fixed and a correct error message will be shown.
